[package]
name = "append"
version = "0.1.0"
authors = ["Artem Khramov <akhramov+appender@pm.me>"]
edition = "2018"

[dependencies]
dotenv_codegen="0.14.1"
diesel = { version = "1.0.0", features = ["sqlite"] }
failure = "0.1.5"
reqwest="0.9.19"
serde="1.0.97"
serde_json="1.0.40"